chore:
keyshade-xyz/keyshade pull request #106
Opened 2024-02-03 05:42 UTC by SRINJAYDASGUPTA-Git

- [x] '@prisma/client' imported multiple times.
- [x] Merge the functions into one with an additional forRegisteredUser flag
- [x] Replace as with upper case format AS.

## Description

- Replaced `as` to `AS` in `/apps/web/Dockerfile` and `/apps/api/DockerFile`
- Merged two separate imports from `@prisma/client` into one in `apps/api/src/common/api-key-roles.ts`
- Added the `forRegisteredUser` boolean flag in `apps/api/src/mail/services/interface.service.ts`
- Commented out `async workspaceInvitationMailForNonRegisteredUser` and added the `forRegisteredUser` flag in `async workspaceInvitationMailForRegisteredUser` in `apps/api/src/mail/services/mail.service.ts`
- Commented out `async workspaceInvitationMailForNonRegisteredUser` and refactored the log statement according to the value of `forRegisteredUser` flag in `apps/api/src/mail/services/mock.service.ts`

Fixes #104 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

@rajdip-b 
## Screenshots of relevant screens

![image](https://github.com/keyshade-xyz/keyshade/assets/70833470/3773feb0-12d3-47a6-89be-17afee843363)
![image](https://github.com/keyshade-xyz/keyshade/assets/70833470/2eeccbaa-c342-41b0-ac45-2acef2eb4c1f)
![image](https://github.com/keyshade-xyz/keyshade/assets/70833470/83c0b902-d8d2-462c-abbc-e816911cfd25)
![image](https://github.com/keyshade-xyz/keyshade/assets/70833470/9d7f02e5-e918-4a2a-afc7-58c852e4cb1e)
![image](https://github.com/keyshade-xyz/keyshade/assets/70833470/a5b3911e-a772-4ad8-b649-796fe0282907)
![image](https://github.com/keyshade-xyz/keyshade/assets/70833470/fb2f02e7-5cbc-4c98-9b5f-2514e0e7da31)

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-02-03 05:50 UTC, rajdip-b requested changes
Left some reviews. Also, the unit tests are failing. So make sure you have run them and they work.

2024-02-03 05:50 UTC, rajdip-b commented on apps/api/src/mail/services/interface.service.ts
> +  // workspaceInvitationMailForNonRegisteredUser(
Remove the commented out method

2024-02-03 05:50 UTC, rajdip-b commented on apps/api/src/mail/services/interface.service.ts
> +    forRegisteredUser: boolean
Change the name of the function to something more meaningful since we are now adding this flag!

2024-02-03 05:50 UTC, rajdip-b commented on apps/api/src/mail/services/mail.service.ts
> +    forRegisteredUser: boolean
You would need to use this flag to decide on the type of message that would be sent to the user

2024-02-03 05:50 UTC, rajdip-b commented on apps/api/src/mail/services/mock.service.ts
> +  // async workspaceInvitationMailForNonRegisteredUser(
Remove this block aswell

2024-02-03 05:54 UTC, rajdip-b commented
@SRINJAYDASGUPTA-Git 
![image](https://github.com/keyshade-xyz/keyshade/assets/83924254/8ef40471-dad6-46e1-be80-066e1ed74bfa)
also, implement this in the code!

2024-02-03 06:04 UTC, SRINJAYDASGUPTA-Git commented on apps/api/src/mail/services/mock.service.ts
> +  // async workspaceInvitationMailForNonRegisteredUser(
done

2024-02-03 06:13 UTC, rajdip-b commented
@SRINJAYDASGUPTA-Git the unit tests are still failing https://github.com/keyshade-xyz/keyshade/actions/runs/7765045160/job/21179240008?pr=106#step:9:212

2024-02-03 06:15 UTC, rajdip-b requested changes
The isses are resolved. Make sure the tests passes then we can merge this

2024-02-03 06:19 UTC, SRINJAYDASGUPTA-Git commented
Please check if its ok now @rajdip-b

2024-02-03 06:33 UTC, merged

2024-02-09 06:19 UTC, rajdip-b commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: