fix(auth): loading github module optionally
keyshade-xyz/keyshade pull request #112
Opened 2024-02-06 17:11 UTC by HarshPatel5940

## Description
This pull request refactors the Github authentication module to load the Github module optionally. It also adds a new service called `GithubEnvService` to handle Github environment configurations. The `GithubStrategy` class now accepts the Github credentials as constructor parameters. Additionally, the `AuthController` now checks if Github login is enabled before redirecting to the Github OAuth endpoint.

Fixes #107 

## Dependencies
> no

## Mentions
@rajdip-b 

![image](https://github.com/keyshade-xyz/keyshade/assets/83941233/247541df-c399-4b07-9330-c9fa82d076e8)

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update
- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-02-06 18:11 UTC, rajdip-b requested changes
Alright I went through the changes, and the logic looks fine to me. (Thanks for the screenshot ❤️ )

Here's a list of things I would like you to do to make this complete:
- [ ] Create another module named `config`: `cd apps/api && nest g module config`
- [ ] Create a folder named `oauth-stratergy` and move the `github.stratergy.ts` file to this folder
- [ ] Create a folder inside that module named `factory`
- [ ] Add an interface inside it named `OAuthStratergyFactory (oauth-stratergy.factory.ts)` with just one function in it -> `<T extends PassportStratergy> createOAuthStratergy(): T`
- [ ] Add a service class named `GitHubOAuthStratergyFactory (github-stratergy.factory.ts)` in the `factory` folder, implement the `OAuthStratergy` interface, and combine the code that you wrote in `GithubEnvService`. This new factory class will have two roles: a private function to check if github is enabled or not, a public function `createOAuthStratergy` that will do the work you are currently doing in the provider section of the `auth.module.ts` file.
- [ ] Export these files from the config folder using the `exports` array.
- [ ] Import them in the `auth.module.ts` and fill in the gaps

If you can spot, I'm motivating you to use factory pattern for this one. This is for a bigger cause:
- We will have multiple auth providers in future (even metamask wallet)
- We will have a couple of services (sentry for example) that we would want to configure in a similar manner. 

Your PR here would lay down the fundamentals of a very big architecture of our repository ❤️

2024-02-07 01:20 UTC, HarshPatel5940 commented on apps/api/src/auth/auth.module.ts
> +          Logger.warn('Github Login Is Not Enabled In This Environment')
Got it.

2024-02-07 01:22 UTC, HarshPatel5940 commented
Thank you @rajdip-b for your time writing these detailed steps, it will immensely help me. I will make the necessary changes as soon as time permits and let you know here.

2024-02-07 04:33 UTC, rajdip-b commented
Awesome man @HarshPatel5940 !! Really thanks for doing all this.

2024-02-07 04:47 UTC, HarshPatel5940 commented
> Awesome man @HarshPatel5940 !! Really thanks for doing all this.

Thanks to you as well for the detailed review!

2024-02-07 06:40 UTC, rajdip-b commented
@HarshPatel5940 I'm working on another branch that aims to fix some issues with the CI and also add a functionality to the api-keys. Once that's done, I'll update your branch and make the review again!

2024-02-07 11:23 UTC, merged

2024-02-09 06:19 UTC, rajdip-b commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: