Replaced OTP code from alphanumeric to numeric
keyshade-xyz/keyshade pull request #230
Opened 2024-05-19 08:19 UTC by Ritika1705

## Description

Replaced RandomUUid with Math.Random <br />

Fixes #211 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-05-19 08:27 UTC, rajdip-b commented
Hey @Ritika1705, thanks for making this PR! I will check this ASAP and try to merge it.

2024-05-19 08:28 UTC, rajdip-b requested changes

2024-05-19 08:28 UTC, rajdip-b commented on apps/api/src/auth/service/auth.service.ts
`import { randomUUID } from 'crypto'`

Can you remove this import?

2024-05-19 13:23 UTC, kriptonian1 commented
Hey @Ritika1705 and @rajdip-b using `Math.random` is not the most secure way to generate opt you can read this amazing discussion in stackexchange crypto channel to know more on why [link](https://crypto.stackexchange.com/questions/11779/why-not-just-generate-random-strings-for-one-time-password-otp). I will rather recommend to use TOTP for that you can use [otplib](https://www.npmjs.com/package/otplib). Now, using math.random is not secure because it's a pseudo random number generator, which is not cryptographically secure.

2024-05-20 05:56 UTC, rajdip-b commented
@Ritika1705 hey! did you encounter any issue in the implementation? We are eager to merge your PR!

2024-05-20 05:59 UTC, Ritika1705 commented
Hi,
Got caught up with some work. Will try to finish it by eod. Thankyou

On Mon, 20 May 2024 at 11:26 AM, Rajdip Bhattacharya <
***@***.***> wrote:

> @Ritika1705 <https://github.com/Ritika1705> hey! did you encounter any
> issue in the implementation? We are eager to merge your PR!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/keyshade-xyz/keyshade/pull/230#issuecomment-2119722096>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANAPAFWD2HHJCB2ZI5M5EV3ZDGGCJAVCNFSM6AAAAABH6FJGQCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJZG4ZDEMBZGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-20 06:02 UTC, rajdip-b commented
Oh! Alright no issues! Whenever you are free.

2024-05-20 11:06 UTC, Ritika1705 commented on apps/api/src/auth/service/auth.service.ts
Hi @rajdip-b, i have removed the import.

2024-05-20 11:08 UTC, Ritika1705 commented
For better secure code generation, we can follow this article: https://medium.com/getpowerplay/a-one-time-password-otp-generator-npm-library-based-on-nanoid-79821a173798

2024-05-20 14:17 UTC, rajdip-b commented
Hey @Ritika1705, I went through some articles, and I feel that we can use the already existing `crypto` library. Maybe you can try out this suggestion?

```ts
crypto.randomBytes(3).toString('hex'),
 ```

I'm not sure how it will perform, but let's keep things simple - and use crypto package.

2024-05-20 18:08 UTC, Ritika1705 commented
> Hey @Ritika1705, I went through some articles, and I feel that we can use the already existing `crypto` library. Maybe you can try out this suggestion?
> 
> ```ts
> crypto.randomBytes(3).toString('hex'),
> ```
> 
> I'm not sure how it will perform, but let's keep things simple - and use crypto package.

Hi @rajdip-b , I have upadated the code to use crypto package. 

The code BigInt(\0x${crypto.randomUUID().replace(/-/g, '')}`).toString().substring(0, 6)` generates a 6-character string by following these steps:

- Generate a UUID: crypto.randomUUID() generates a version 4 UUID, which looks something like 550e8400-e29b-41d4-a716-446655440000.
- Remove Hyphens: .replace(/-/g, '') removes all the hyphens from the UUID, resulting in a string like 550e8400e29b41d4a716446655440000.
- Convert to BigInt: BigInt(\0x${uuid}`)converts this hexadecimal string to a BigInt. The0x` prefix indicates that the string is in hexadecimal format.
- Convert to String: .toString() converts the BigInt to its decimal string representation.
- Extract 6 Digits: .substring(0, 6) takes the first 6 characters from the decimal string

2024-05-21 04:51 UTC, rajdip-b approved these changes
LGTM!

2024-05-21 04:57 UTC, merged

2024-05-24 13:59 UTC, rajdip-b commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: