fix(docker): Grant correct permissions to docker image
keyshade-xyz/keyshade pull request #251
Opened 2024-05-30 19:11 UTC by Ratnesh2003

## Description

Added `700` permission to the directory created by the postgres db in docker compose. <br />
A

Fixes #245 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

@rajdip-b 

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-05-30 19:56 UTC, rajdip-b requested changes

2024-05-30 19:56 UTC, rajdip-b commented on pnpm-lock.yaml
Not sure why this file was changed.

2024-05-30 20:18 UTC, Ratnesh2003 commented on pnpm-lock.yaml
This confused me as well. I just installed all the dependencies again because of some issue I faced in my machine. 
That changed the lock file as well.

2024-05-31 03:57 UTC, rajdip-b commented on pnpm-lock.yaml
Could you try doing `git restore .`, and then running `pnpm i`? See if it is causing the lock file to change.

2024-05-31 10:31 UTC, Ratnesh2003 commented on pnpm-lock.yaml
It still changes the lock file completely. I tried your method and also try to hard reset back to `develop` and then do `pnpm i`. But same results :cry:

2024-05-31 12:39 UTC, rajdip-b commented on pnpm-lock.yaml
okay no worries

2024-05-31 12:39 UTC, rajdip-b approved these changes

2024-05-31 12:40 UTC, merged

2024-06-12 08:14 UTC, rajdip-b commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: