chore(web): Update Terms and Conditions and Privacy Policy
keyshade-xyz/keyshade pull request #282
Opened 2024-06-16 23:20 UTC by Aleesssino

## Description

- Updated Terms and Conditions and Privacy Policy documents to reflect current policies and legal requirements.
- Fixed style prop error in Privacy Policy markdown:
  Replace 
```
  <span style="text-decoration:underline;">Withdrawing your consent:</span>
```
  with 
```
   <span style={{ textDecoration: 'underline' }}>Withdrawing your consent:</span>
```
  to correctly apply inline style formatting using JSX. <br />

Fixes #281 

## Mentions

@kriptonian1 

## Developer's checklist

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-check on my work

**If changes are made in the code:**

- [X] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [X] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [X] There are no UI/UX issues

2024-06-17 05:56 UTC, rajdip-b commented
@kriptonian1 yo ser drop your reviews!

2024-06-17 05:56 UTC, rajdip-b approved these changes
LGTM

2024-06-17 07:22 UTC, kriptonian1 requested changes
I think after this updates it should be good to merge

2024-06-17 07:22 UTC, kriptonian1 commented on apps/web/src/app/(main)/(mdx)/privacy/page.mdx
>  Our servers are located in. If you are accessing our Services from outside, please be aware that your information may be transferred to, stored, and processed by us in our facilities and by those thi
update this too `Our servers are located in India. If you are accessing our Services from outside, please be aware that your information may be transferred to, stored, and processed by us in our facilities and by those third parties with whom we may share your personal information (see "WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?" above), in India and other countries.`

2024-06-17 07:22 UTC, kriptonian1 commented on apps/web/src/app/(main)/(mdx)/privacy/page.mdx
>  We do not knowingly solicit data from or market to children under 18 years of age. By using the Services, you represent that you are at least 18 or that you are the parent or guardian of such a minor
Update this `We do not knowingly solicit data from or market to children under 18 years of age.` to `We do not knowingly solicit data from or market to individuals under the age of 18.`

2024-06-17 07:22 UTC, kriptonian1 commented on apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
> +Last updated: April 11, 2024.
Update the date to `11 April 2024`

2024-06-17 13:20 UTC, Aleesssino commented on apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
I added some spacing for readability.

2024-06-19 13:36 UTC, rajdip-b commented
@kriptonian1 can you review this now?

2024-06-26 05:15 UTC, kriptonian1 commented
Sorry guys, I was not available. Let me review it for you

2024-06-26 05:24 UTC, kriptonian1 requested changes
There are just some formatting issues with the email, after fixing this we will be good to merge ig

2024-06-26 05:24 UTC, kriptonian1 commented on apps/web/src/app/(main)/(mdx)/privacy/page.mdx
> +support@keyshade.xyz
this should be `[support@keyshade.xyz](mailto:support@keyshade.xyz)`

2024-06-26 05:24 UTC, kriptonian1 commented on apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
> +You can contact us by phone at, by email at support@keyshade.xyz, or by mail at 30/17 SHIB CHANDRA CHATTERJEE STRT, Howrah, West Bengal 711202, India.
format this email as `[support@keyshade.xyz](mailto:support@keyshade.xyz)`

2024-06-26 05:24 UTC, kriptonian1 commented on apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
> +We will provide you with prior notice of any scheduled changes to the services you are using. The modified legal terms will become effective upon posting or notifying you at support@keyshade.xyz, as
format the email as `[support@keyshade.xyz](mailto:support@keyshade.xyz)`

2024-06-26 05:24 UTC, kriptonian1 commented on apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
> +If you wish to make any use of the Services, Content, or Marks other than as set out in this section or elsewhere in our Legal Terms, please address your request to: support@keyshade.xyz. If we ever
format the email as `[support@keyshade.xyz](mailto:support@keyshade.xyz)`

2024-06-26 05:24 UTC, kriptonian1 commented on apps/web/src/app/(main)/(mdx)/terms_and_condition/page.mdx
> +All purchases are non-refundable. You can cancel your subscription at any time by logging into your account. Your cancellation will take effect at the end of the current paid term. If you have any qu
format the email to `[support@keyshade.xyz](mailto:support@keyshade.xyz)`

2024-06-27 15:17 UTC, kriptonian1 approved these changes

2024-06-27 16:04 UTC, rajdip-b approved these changes

2024-06-27 16:04 UTC, merged