feature: added requireRestart param
keyshade-xyz/keyshade pull request #286
Opened 2024-06-25 19:33 UTC by yogesh1801

## Description

Added requireRestart param

Fixes #283 

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-06-25 19:36 UTC, rajdip-b commented
Hey bro! Glad that you put up the PR. Are you attempting this for FOSS hack? If so, the PR will need to wait. If not, we can start reviewing it asap!

2024-06-25 19:38 UTC, yogesh1801 commented
@rajdip-b this PR is my attempt to get familiar with the codebase, will attempt fosshack later

2024-06-26 05:26 UTC, rajdip-b requested changes

2024-06-26 05:26 UTC, rajdip-b commented on apps/api/src/prisma/schema.prisma
> +  requireRestart Boolean        @default(false)
You would need to format the db once: `pnpm db:format`

2024-06-26 05:30 UTC, rajdip-b requested changes
Update the interface over [here](https://github.com/keyshade-xyz/keyshade/blob/36619b0ab31416f8171198cdb1ccadb525c21fee/apps/api/src/socket/socket.types.ts#L7)

2024-06-26 08:36 UTC, rajdip-b requested changes

2024-06-26 08:36 UTC, rajdip-b commented on apps/api/src/prisma/migrations/20240625190757_new/migration.sql
Oh missed this one, can you rename the migration folder to something more meaningful? Maybe: `<migration_id>_add_require_restart_field`

2024-06-26 08:52 UTC, rajdip-b approved these changes

2024-06-26 10:20 UTC, merged