feat(api-client): Create controller for Secret module
keyshade-xyz/keyshade pull request #396
Opened 2024-07-28 05:39 UTC by vr-varad

## Description

Api client Controller for Secret Module

Fixes #352 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-07-28 07:54 UTC, vr-varad commented
@rajdip-b Can u give it a look whenever you are free.

2024-07-28 09:44 UTC, rajdip-b requested changes

2024-07-28 09:44 UTC, rajdip-b commented on packages/api-client/src/types/secret.types.d.ts
> +export interface GetAllSecretsOfEnvironmentResponse {
Please check the return type from postman or make a query to this endpoint yourself.

2024-07-28 09:44 UTC, rajdip-b commented on packages/api-client/src/types/secret.types.d.ts
> +  secret: any
Refrain from using `any`

2024-07-28 09:44 UTC, rajdip-b commented on packages/api-client/src/types/secret.types.d.ts
> +  rotateAfter?: string
copy the exact type of rotateAfter from the dto in api

2024-07-28 18:22 UTC, rajdip-b requested changes

2024-07-28 18:22 UTC, rajdip-b commented on packages/api-client/src/types/secret.types.d.ts
> +export interface GetAllSecretsOfProjectResponse {
The data should be returned in `items`. Modify the function and the type accordingly.

2024-07-28 18:22 UTC, rajdip-b commented on packages/api-client/src/types/secret.types.d.ts
> +  page?: number
This endpoint wont have pagination

2024-08-02 12:25 UTC, rajdip-b commented
@vr-varad can you start with this pr? please make the changes as we have done in environments controller.

2024-08-02 13:00 UTC, vr-varad commented
@rajdip-b Yeah Sure

2024-08-03 04:18 UTC, vr-varad commented
@rajdip-b Can u review it whenever u are free

2024-08-03 05:56 UTC, rajdip-b approved these changes
LGTM

2024-08-03 05:56 UTC, merged