Migrate CLI to Bun
keyshade-xyz/keyshade pull request #400
Opened 2024-07-28 14:27 UTC by RanitMukherjee

## Description

_As of now, only have modified the package.json of the CLI_ <br />

Fixes #363 

## Future Improvements

_This is surely incomplete as of now & the only motivation behind such a low effort PR is to understand the requirements better & actually get the work done._

## Mentions

 @rajdip-b 

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-07-28 17:24 UTC, rajdip-b commented
It's true that the installation will be a pain initially. We will have the docs up for it. 

I think we can't migrate the API to bun because NestJS isnt supported. So, we are mostly aiming for the API Client and CLI to be migrated. And then if possible, we would migrate the frontend.

2024-07-28 17:25 UTC, rajdip-b requested changes

2024-07-28 17:25 UTC, rajdip-b commented on apps/cli/package.json
Maybe you can swap out the existing commands with the new ones and see how it goes?

2024-07-29 04:41 UTC, RanitMukherjee commented
> It's true that the installation will be a pain initially. We will have the docs up for it.
> 
> I think we can't migrate the API to bun because NestJS isnt supported. So, we are mostly aiming for the API Client and CLI to be migrated. And then if possible, we would migrate the frontend.

I just checked out Bun Issue in regard to NestJS compatability, and it seems as of 21st June 2024, most of support for NestJS has been established & separate issues regarding edge cases/specific troubleshooting are to be created. Can you clarify in regard to details in regard to specific issues we been encountering, maybe a issue can be raised against the same & once sorted, a full migration to Bun might not be far, thus allowing a simpler set up experience as well.

2024-07-29 05:15 UTC, rajdip-b commented
We won't know for sure what exactly the blockers might be, until and unless someone starts working on it. That's why, we have parked it for the very end.

2024-08-23 11:21 UTC, Jarred-Sumner commented
let us know if you run into any issues with nestjs in bun

2024-08-23 15:15 UTC, rajdip-b commented
@Jarred-Sumner thanks! We are tracking our NestJS migration in #275. We will surely hit you up in case we hit a dead end :D

2024-11-02 11:36 UTC, rajdip-b commented
We are closing this PR atm. We would like to stall it for later, and probably let our internal team handle the feature since it's a bit complex. Thanks for your efforts though @RanitMukherjee!

2024-11-02 11:36 UTC, closed without merging