feat(cli): Add release pipeline (#297)
keyshade-xyz/keyshade pull request #407
Opened 2024-08-02 08:08 UTC by Kiranchaudhary537

## Description

_Give a summary of the change that you have made_ <br />

Fixes #[ISSUENO]

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-08-02 08:29 UTC, rajdip-b requested changes

2024-08-02 08:29 UTC, rajdip-b commented on .github/workflows/deploy-cli.yml
> +    pull_request:
Not on pull requests

2024-08-02 08:29 UTC, rajdip-b commented on .github/workflows/deploy-cli.yml
> +      - name: Bump version and generate changelog
We don't want this step

2024-08-02 08:29 UTC, rajdip-b commented on .github/workflows/deploy-cli.yml
> +      - name: Publish to NPM
We don't have any publish script either. You would need to come up with one that will publish the cli. And lastly, we want to use `pnpm`, not `npm`

2024-09-16 16:36 UTC, kriptonian1 commented
@Kiranchaudhary537 what's the update man

2024-09-16 16:55 UTC, Kiranchaudhary537 commented
The requested changes have been implemented, and comments have been refactored. Please let me know if anything is missing.

2024-09-17 05:00 UTC, rajdip-b commented
There are a ton of conflicts @Kiranchaudhary537, could you please put up another PR? I believe you haven't made changes to many files.

2024-10-13 15:27 UTC, rajdip-b commented
@Kiranchaudhary537 hey man, are you still on it? We would really like to get this merged

2024-10-14 06:51 UTC, kriptonian1 commented
why is there 472 changed files, you are not supposed to commit everything, you only need to add the files you worked with

2024-10-14 06:57 UTC, rajdip-b commented
I agree, you should close this PR, and make your changes on a newer one.

2024-10-18 12:20 UTC, rajdip-b commented
Closing due to inactivity.

2024-10-18 12:20 UTC, closed without merging