fix(api): Add NotFound exception on passing an invalid roleId while inviting user in workspace
keyshade-xyz/keyshade pull request #408
Opened 2024-08-16 14:37 UTC by PriyobrotoKar

## Description

Added validation to ensure that If a workspace role is provided in the `roleIds` array doesn't exist, a `NotFoundException` is thrown.

Fixes #405 

## Dependencies

No new dependencies were added.

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-08-16 14:48 UTC, rajdip-b requested changes

2024-08-16 14:48 UTC, rajdip-b commented on apps/api/src/workspace/service/workspace.service.ts
The code looks perfect! Just would need a little refactoring. Could you move out the code that you added into a function and then call the function instead?

2024-08-16 14:50 UTC, rajdip-b commented on apps/api/src/workspace/service/workspace.service.ts
> +    )
@PriyobrotoKar also add this suggestion.

2024-08-17 14:13 UTC, PriyobrotoKar commented on apps/api/src/workspace/service/workspace.service.ts
yes, right! Doing it now.

2024-08-17 14:13 UTC, PriyobrotoKar commented on apps/api/src/workspace/service/workspace.service.ts
> +    )
okk 👍

2024-08-17 15:47 UTC, PriyobrotoKar commented
@rajdip-b I have made those changes.

2024-08-17 15:51 UTC, rajdip-b approved these changes

2024-08-17 15:51 UTC, merged