Fixed duplicate Google Logo UI fix
keyshade-xyz/keyshade pull request #450
Opened 2024-09-18 17:01 UTC by prabuddha369

## Description
![image](https://github.com/user-attachments/assets/663985f8-6a71-4dca-89f6-24dcacb6d238)
Added Gitlab logo

Fixes #449 

## Dependencies

NA

## Future Improvements

Linking to the Backend and if i get the figma file , i can add more features !

## Mentions

@rajdip-b 

## Screenshots of relevant screens

![image](https://github.com/user-attachments/assets/b04d8a88-6fd5-43ba-8f99-e27e5e7b1165)

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-09-19 05:42 UTC, rajdip-b commented
@kriptonian1

2024-09-19 06:38 UTC, kriptonian1 requested changes
There are files which are not related to the change you mentioned, so those won't be committed, these files are `packages/secret-scan/src/rules` and `web/src/app/(main)/career`, after these proposed fix we can merge this

2024-09-19 06:38 UTC, kriptonian1 commented on apps/web/src/app/(main)/career/page.tsx
This file is not related to the change you mentioned, so this won't be commited

2024-09-19 06:56 UTC, rajdip-b commented on apps/web/src/app/(main)/career/page.tsx
I don't know why this is coming up every time. Honestly.

2024-09-19 06:56 UTC, rajdip-b commented on apps/web/src/app/(main)/career/page.tsx
P.S., we can have the formatted secret scan files

2024-09-19 07:46 UTC, kriptonian1 commented on apps/web/src/app/(main)/career/page.tsx
I think it is happening because of linting

2024-09-19 16:20 UTC, merged

2024-10-24 12:12 UTC, rajdip-b commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: