docs: Adding documentation for  cli command
keyshade-xyz/keyshade pull request #464
Opened 2024-09-24 16:15 UTC by YuvalBubnovsky

## Description

This PR adds documentation for the `workspace` feature in the CLI, providing users with clear instructions on how to utilize this functionality effectively. <br />

Fixes #[458]

## Dependencies

No new dependencies introduced.

## Future Improvements

Possibly adding examples for common use cases of the `workspace` feature in future documentation updates.

## Mentions

@rajdip-b

## Screenshots of relevant screens

N/A

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [ ] There are no UI/UX issues

### Documentation Update

- [x] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-09-24 16:31 UTC, YuvalBubnovsky commented
@rajdip-b I feel like the bot's suggestion for adding the info about the `delete` command is wrong, from what I've seen in the code (apps/cli/src/commands/workspace/delete.workspace.ts), no such confirmation for deletion exists..

I also think the suggestion for adding usage examples to `list` is redundent, but if you think this is a good idea - I'll add those.

2024-09-24 17:38 UTC, rajdip-b requested changes

2024-09-24 17:38 UTC, rajdip-b commented on docs/cli/workspace.md
> +- [`delete`](#delete): This command is used to delete an existing workspace.
add - 'All data related to this workspace will be permanently lost.'

2024-09-24 17:38 UTC, rajdip-b commented on docs/cli/workspace.md
> +- [`export`](#export): This command is used to export all projects, environments, secrets, variables, and roles of a workspace.
add - 'into JSON format'

2024-09-24 17:38 UTC, rajdip-b commented
> @rajdip-b I feel like the bot's suggestion for adding the info about the `delete` command is wrong, from what I've seen in the code (apps/cli/src/commands/workspace/delete.workspace.ts), no such confirmation for deletion exists..
> 
> I also think the suggestion for adding usage examples to `list` is redundent, but if you think this is a good idea - I'll add those.

Hmm, I think you have a valid point in here. Cool, you can drop that suggestion!

2024-09-25 07:12 UTC, YuvalBubnovsky commented
@rajdip-b 
added 'into JSON format' and rebased.

2024-09-25 15:02 UTC, rajdip-b approved these changes

2024-09-25 15:03 UTC, merged

2024-10-24 12:11 UTC, rajdip-b commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: