fix(api,api-client) :Add environmentSlug in multiple places across the variable module
keyshade-xyz/keyshade pull request #468
Opened 2024-09-26 09:50 UTC by Nil2000

## Description

Add `environmentSlug` in multiple places across the `variable` module <br />

Fixes #431 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-09-26 10:10 UTC, Nil2000 commented
Hi @rajdip-b , Require some help here.

2024-09-29 05:19 UTC, rajdip-b requested changes
![image](https://github.com/user-attachments/assets/373dbc6c-e140-4417-89fb-437f18d1c281)
In places where we are selecting both environmentId and environment slug, its better to include it by using `environment.id` and `environment.slug`:

```
      environment: {
        id: true
        slug: true
      }
```

2024-09-29 11:16 UTC, Nil2000 commented
> ![image](https://private-user-images.githubusercontent.com/83924254/371824654-373dbc6c-e140-4417-89fb-437f18d1c281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDc3NjEsIm5iZiI6MTcyNzYwNzQ2MSwicGF0aCI6Ii84MzkyNDI1NC8zNzE4MjQ2NTQtMzczZGJjNmMtZTE0MC00NDE3LTg5ZmItNDM3ZjE4ZDFjMjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDEwNTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3Y2EzNmNhOWU4ZGQ3MTFmZGMyNmQyMWViYWU5ZTcxYzkyMmUwZjA4YTRiMDk0YjA4NTJlYTFiYTQxM2JlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f2cLTPYPP80ZyytZaTXGeKp-JgDq7gzv5rFymPMadHs) 
In places where we are selecting both environmentId and environment slug, its better to include it by using `environment.id` and `environment.slug`:
> 
> ```
>       environment: {
>         id: true
>         slug: true
>       }
> ```

Ok made these changes but did you notice about the `environment2` test mentioned earlier? It is still coming.

![image](https://github.com/user-attachments/assets/d997f416-4bde-4bca-be1d-fc0795009a5a)

2024-09-29 17:38 UTC, rajdip-b approved these changes

2024-09-29 17:38 UTC, rajdip-b requested changes
This step is failing: https://github.com/keyshade-xyz/keyshade/actions/runs/11092075120/job/30816652494?pr=468#step:10:486

2024-09-29 17:45 UTC, Nil2000 commented
> This step is failing: https://github.com/keyshade-xyz/keyshade/actions/runs/11092075120/job/30816652494?pr=468#step:10:486

Yeah already mentioned the issue this is always pointing to `environment-1-0` slug or `Environment 1` though I have pointed that to `environment1.`

2024-10-15 04:27 UTC, rajdip-b commented
@Nil2000 can you please add this change I mentioned?

> @Nil2000 sorry about the delay, i have fixed the error. I would just need you to remove `environmentId` and have `environment.id` everywhere like i mentioned earlier.

2024-10-15 04:33 UTC, Nil2000 commented
> @Nil2000 can you please add this change I mentioned?
> 
> > @Nil2000 sorry about the delay, i have fixed the error. I would just need you to remove `environmentId` and have `environment.id` everywhere like i mentioned earlier.

Working on it. Would be done by today

2024-10-15 16:33 UTC, Nil2000 commented
@rajdip-b The test issue is still present
![image](https://github.com/user-attachments/assets/b597495d-6445-43a0-a8e9-dd985f334fd6)

2024-10-15 16:41 UTC, rajdip-b requested changes
- The last few changes that you made break a lot of things, and also isn't required. You are required to send back the data in the format that i have already mentioned in the comment above. This reqires you to just change how the environmentId is "included", and not make changes to the business logic.
- I fixed the tests when I last updated the PR. You can also check that in https://github.com/keyshade-xyz/keyshade/actions/runs/11349562441/job/31565953148

2024-10-15 16:46 UTC, Nil2000 commented on apps/api/src/variable/variable.e2e.spec.ts
> +      expect(body.versions[0].environment.slug).toBe(environment2.slug)
This should point to `environment2.slug` since this version is being pointed to `environment2.id`

2024-10-16 17:47 UTC, rajdip-b requested changes
Just double-check the `api-client` package. The rest of the changes look solid.

2024-10-16 17:47 UTC, rajdip-b commented on packages/api-client/tests/variable.spec.ts
>      expect(variable.data.versions[0].environmentId).toBe(environment.id)
I don't think this would be present anymore. And if its still being returned, then you might have missed something.

2024-10-16 17:47 UTC, rajdip-b commented on packages/api-client/tests/variable.spec.ts
>      expect(updateVariable.data.updatedVersions[0].environmentId).toBe(
Same goes for here.

2024-10-17 14:58 UTC, merged

2024-10-24 12:11 UTC, rajdip-b commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: