feat(cli): implement commands to get, list, update, and delete, workspace roles
keyshade-xyz/keyshade pull request #469
Opened 2024-09-29 11:51 UTC by Meeran-Tofiq

## Description

_Give a summary of the change that you have made_ <br />
I have made 4 commands that are sub-commands of `role`. the commands are `get`, `list`, `update`, and `delete`. Update has the ability to change name, description, color code, authorities, and projects.  

Fixes #[447]

## Dependencies

_Mention any dependencies/packages used_
N/A

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_
The authorities and projects are updated poorly. If a role has a few authorities already, and you need to add a new one, you have to give the command the entire list of all authorities you already have + the authorities you need. Same for projects. This is tedious, arduous, and annoying. If possible and applicable, in the future there should be another sub-command for project and for authorities.

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

![Screenshot from 2024-09-28 15-34-13](https://github.com/user-attachments/assets/084651fb-3aa1-4019-b337-5dd67d1c52ae)
![Screenshot from 2024-09-28 15-34-22](https://github.com/user-attachments/assets/1d8cc1ef-78a1-4042-84f5-1d5d89e43455)
![Screenshot from 2024-09-28 15-34-55](https://github.com/user-attachments/assets/dbc35dbf-a592-4d13-8571-d4d53f9f3ef2)
![Screenshot from 2024-09-29 14-48-34](https://github.com/user-attachments/assets/4e603134-4383-4e02-8558-dd2bbde2bd63)
![Screenshot from 2024-09-28 15-35-56](https://github.com/user-attachments/assets/bb7d195f-9ac7-40f4-b9a9-e7631416a7a7)
![Screenshot from 2024-09-29 14-40-20](https://github.com/user-attachments/assets/60f892bc-6a71-416c-8091-06470b2e2229)

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [x] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-09-29 17:37 UTC, rajdip-b requested changes

2024-09-29 17:37 UTC, rajdip-b commented on apps/cli/src/commands/workspace/role/list.role.ts
Can you please add pagination? Please refer these sections:

- https://github.com/keyshade-xyz/keyshade/blob/develop/apps/cli/src/util/pagination-options.ts
- https://github.com/keyshade-xyz/keyshade/blob/bc04be4de99c0b4e86196a1e5e0fbc14f8d8b499/apps/cli/src/commands/environment/list.environment.ts#L29-L31
- https://github.com/keyshade-xyz/keyshade/blob/bc04be4de99c0b4e86196a1e5e0fbc14f8d8b499/apps/cli/src/commands/environment/list.environment.ts#L48-L55

2024-10-01 07:06 UTC, Meeran-Tofiq commented on apps/cli/src/commands/workspace/role/list.role.ts
Yes sir :saluting_face:

2024-10-01 16:33 UTC, rajdip-b approved these changes

2024-10-01 16:35 UTC, merged

2024-10-24 12:11 UTC, rajdip-b commented
:tada: This PR is included in version 2.6.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v2.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: