feat: Add email template for inviting user to project
keyshade-xyz/keyshade pull request #480
Opened 2024-10-06 17:41 UTC by Allan2000-Git

## Description

This PR adds an email template for inviting user to project. It provides users with key information regarding the project name
project joining URL, invited by, invited on and invitation role.

Fixes #54 

## Dependencies

No new dependencies introduced.

## Future Improvements

N/A

## Mentions

@rajdip-b 

## Screenshots of relevant screens

![Screenshot 2024-10-06 224949](https://github.com/user-attachments/assets/574c6a16-f5dd-44ad-9621-aef2e46a5676)

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-10-07 04:58 UTC, rajdip-b commented
Hey man, that's some impressive work. Although again, the scope of this issue is outdated. So it would be Workspace, not project. And gladly, we already have a function for workspace. All you would need is to update the stylings of that mail template.

Additionally, I would like to take a call from @kriptonian1 @darksaiii about the design decisions.

2024-10-07 05:50 UTC, kriptonian1 commented
@Allan2000-Git I like the work, but can you do the implementation in [React email](https://react.email/), they have better support for all email client and also have accessibility for clients which doesn't support HTML.

2024-10-07 07:06 UTC, Allan2000-Git commented
@rajdip-b Will rename project to workspace.
@kriptonian1 I guess all the templates are written in plain HTML & CSS in `mail.service.ts`. Should I change everyone of them or just keep the scope for the current PR?

2024-10-07 08:50 UTC, kriptonian1 commented
> @rajdip-b Will rename project to workspace. @kriptonian1 I guess all the templates are written in plain HTML & CSS in `mail.service.ts`. Should I change everyone of them or just keep the scope for the current PR?

@rajdip-b should we make a new issue for this

2024-10-08 07:24 UTC, rajdip-b commented
A new PR would be really great. I don't think we need a new issue for that, adding hacktoberfest-accepted to the PR should be enough.

2024-10-12 20:41 UTC, kriptonian1 commented
> A new PR would be really great. I don't think we need a new issue for that, adding hacktoberfest-accepted to the PR should be enough.

Yes, as per as I know, they just count the PR with `hacktoberfest-accepted` tag

2024-10-13 11:16 UTC, rajdip-b commented
> Hey man, that's some impressive work. Although again, the scope of this issue is outdated. So it would be Workspace, not project. And gladly, we already have a function for workspace. All you would need is to update the stylings of that mail template.
> 
> Additionally, I would like to take a call from @kriptonian1 @darksaiii about the design decisions.

@Allan2000-Git if you can implement these changes, I will be happy to merge.

2024-10-13 11:31 UTC, Allan2000-Git commented
> > Hey man, that's some impressive work. Although again, the scope of this issue is outdated. So it would be Workspace, not project. And gladly, we already have a function for workspace. All you would need is to update the stylings of that mail template.
> > Additionally, I would like to take a call from @kriptonian1 @darksaiii about the design decisions.
> 
> @Allan2000-Git if you can implement these changes, I will be happy to merge.

@rajdip-b Since the template has to be designed using `react-email`, it's bit difficult since I'm not able to preview the code. So would need help there.

2024-10-13 12:03 UTC, rajdip-b commented
@kriptonian1 can you please help him out?

2024-10-13 16:04 UTC, kriptonian1 commented
> > > Hey man, that's some impressive work. Although again, the scope of this issue is outdated. So it would be Workspace, not project. And gladly, we already have a function for workspace. All you would need is to update the stylings of that mail template.
> > > Additionally, I would like to take a call from @kriptonian1 @darksaiii about the design decisions.
> > 
> > @Allan2000-Git if you can implement these changes, I will be happy to merge.
> 
> @rajdip-b Since the template has to be designed using `react-email`, it's bit difficult since I'm not able to preview the code. So would need help there.

React email has preview, I'll recommend you to go through the docs and watch some tutorials on YouTube before diving into it.

Here is a video you can refer to

https://youtu.be/pHXHBHdTzrM?si=BAg-r_EYyJmfhK2W

2024-11-02 11:34 UTC, rajdip-b commented
@Allan2000-Git hey buddy, any updates on this?

2024-11-02 11:42 UTC, Allan2000-Git commented
@rajdip-b There's already a PR with react email usage. Since most the things are failing, so I didn't go ahead with the same here.

2024-11-02 11:43 UTC, Allan2000-Git commented
Template is ready and is working fine

2024-11-02 11:44 UTC, Allan2000-Git commented
Can you pull the changes from this [PR](https://github.com/keyshade-xyz/keyshade/pull/476) and check. Would be of great help

2024-12-03 19:23 UTC, rajdip-b requested changes

2024-12-03 19:23 UTC, rajdip-b commented on apps/api/src/mail/services/interface.service.ts
> +  userInvitation(
Rename this to `invitedToWorkspace`

2024-12-03 19:28 UTC, rajdip-b requested changes

2024-12-06 07:36 UTC, rajdip-b requested changes

2024-12-06 07:36 UTC, rajdip-b commented on apps/api/src/mail/services/interface.service.ts
> +    projectName: string,
Not sure why you made this change. Considering the fact that people won't be invited to projects but workspaces.

2024-12-06 07:36 UTC, rajdip-b commented on apps/api/src/mail/emails/workspace-invitation.tsx
> +        <Container style={container}>
I'm pretty sure we can re-use the frames in here. We can convert this into a reusable component where in we can pass the body, the rest would be pre set.

2024-12-07 05:01 UTC, rajdip-b approved these changes

2024-12-07 05:07 UTC, merged

2025-01-23 15:07 UTC, rajdip-b commented
:tada: This PR is included in version 2.9.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v2.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: