fix(cli): Add functionality to operate on Variables
keyshade-xyz/keyshade pull request #514
Opened 2024-10-28 10:56 UTC by anudeeps352

## Description

Add functionality to operate on Variables <br />

Fixes #301 

## Developer's checklist

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-check on my work

**If changes are made in the code:**

- [X] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [X] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [X] There are no UI/UX issues

### Documentation Update

- [X] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-10-29 17:05 UTC, rajdip-b requested changes

2024-10-29 17:05 UTC, rajdip-b commented on apps/cli/src/commands/variable/list.variable.ts
> +        Logger.info('No variable found')
variables**

2024-10-29 17:13 UTC, rajdip-b approved these changes

2024-10-29 17:13 UTC, rajdip-b commented on apps/cli/src/commands/variable/create.variable.ts
> +    })
@anudeeps352 you missed this one

2024-10-29 17:15 UTC, anudeeps352 commented on apps/cli/src/commands/variable/create.variable.ts
> +    })
Ahh man lol. I'm down with fever thats why lol

2024-10-29 17:16 UTC, rajdip-b commented on apps/cli/src/commands/variable/create.variable.ts
> +    })
Take rest bro no rush!

2024-10-29 17:16 UTC, anudeeps352 commented on apps/cli/src/commands/variable/create.variable.ts
> +    })
So just make changes according to the recommendation right ?

2024-10-29 17:22 UTC, rajdip-b approved these changes

2024-10-29 17:22 UTC, merged

2024-11-05 10:02 UTC, rajdip-b commented
:tada: This PR is included in version 2.7.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v2.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: