feat(platform): updated the empty state of dashboard
keyshade-xyz/keyshade pull request #522
Opened 2024-11-07 11:13 UTC by kriptonian1

## Description

Updated the empty state of the dashboard

Fixes #485

## Mentions

@rajdip-b @poswalsameer 

## Screenshots of relevant screens

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/16707eca-6929-4683-a73f-eff111f6792f">

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-11-07 18:35 UTC, rajdip-b approved these changes

2024-11-08 20:22 UTC, poswalsameer requested changes

2024-11-11 05:25 UTC, kriptonian1 commented on apps/platform/src/app/(main)/page.tsx
> +  const [isProjectEmpty, setIsProjectEmpty] = useState(true)
I want to conditionally render the header and the add button, so thought to organise it this way. 
Open for discussion, Should we do it like this or by directly checking the size of the array.

2024-11-11 06:05 UTC, rajdip-b commented on apps/platform/src/app/(main)/page.tsx
> +  const [isProjectEmpty, setIsProjectEmpty] = useState(true)
I think using the array size would be better. We should release memory wherever we can.

2024-11-11 14:32 UTC, poswalsameer commented on apps/platform/src/app/(main)/page.tsx
> +  const [isProjectEmpty, setIsProjectEmpty] = useState(true)
> I want to conditionally render the header and the add button, so thought to organise it this way. Open for discussion, Should we do it like this or by directly checking the size of the array. @poswalsameer @rajdip-b

Got your point, but the conditional rendering can also be done through the size of the `projects` array, so I think this state can be ignored for now. Although, this won't be a big optimization but still we can go with this if we want to.

2024-11-13 05:26 UTC, rajdip-b commented on apps/platform/src/app/(main)/page.tsx
> +  const [isProjectEmpty, setIsProjectEmpty] = useState(true)
@kriptonian1 ig you shoud revert to using array size and we can close this

2024-11-14 05:32 UTC, kriptonian1 commented on apps/platform/src/app/(main)/page.tsx
> +  const [isProjectEmpty, setIsProjectEmpty] = useState(true)
okey will do that

2024-11-26 05:56 UTC, merged