perf: #176 Optimized the api Dockerfile for better build time.
keyshade-xyz/keyshade pull request #527
Opened 2024-11-10 16:55 UTC by kash2104

## Description

- Efficient Caching: Optimized order of operations to leverage Docker’s build cache more effectively.
- Removed Unnecessary Dependency: Retained only the necessary dependencies required for the /api service, removing any unnecessary packages that were previously included.

Fixes #[176]

## Dependencies

N/A

## Future Improvements

N/A

## Mentions

@rajdip-b 

## Screenshots of relevant screens

N/A

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-11-11 05:14 UTC, rajdip-b commented
@kash2104 remember to tag your pr when you create your pr.

2024-11-11 05:19 UTC, rajdip-b requested changes

2024-11-11 05:19 UTC, rajdip-b commented on apps/api/Dockerfile
> +pnpm install --ignore-scripts --frozen-lockfile && \
Could you use some tabs in here to ensure proper formatting?

2024-11-11 05:57 UTC, rajdip-b requested changes
- ![image](https://github.com/user-attachments/assets/5aa5bdc2-7ea7-4610-b213-8e73fd2d0226)
Getting this error on running `docker run --rm --network host --name ks-api --env-file .env ks-api`
- ![image](https://github.com/user-attachments/assets/c1f0c09e-485a-4e6e-946d-d4a4d0acb3ba)
Perhaps you could change the app location in the docker image to just be inside `/app`, and not `/app/api`

2024-11-13 11:38 UTC, kash2104 commented
@rajdip-b Since this is a dockerfile for api do we need the packages and package.json of the root folder?

2024-11-13 14:59 UTC, kash2104 commented
@rajdip-b I changed the app location to /app. Since this Dockerfile is for api, do we need the packages and root package.json?

2024-11-14 11:36 UTC, rajdip-b commented
The compiled version should have all the necessary dependencies. That would go into the 2nd stage. So i believe that you wont actually need to manually delete anything.

2024-11-17 13:06 UTC, rajdip-b requested changes
I'm still getting errors. 
![image](https://github.com/user-attachments/assets/a3ceabc4-85f9-4125-8e01-db349a380c33)

I would recommend you to try building this locally on your device using `pnpm docker:build:api` and then running the container using `pnpm docker:run:api`

2025-02-23 10:18 UTC, closed without merging