feat(schema, api-client): Migrate environment types and schemas to @keyshade/schema
keyshade-xyz/keyshade pull request #538
Opened 2024-11-16 11:50 UTC by muntaxir4

## Description

**`@keyshade/schema`**
- Add schemas and types for environment.
- Add tests for environment schemas.
- Export environment schemas from `index` and its types  from `index.types`
- Remove existing `environment.ts`. Modify `project` schema to include new `CreateEnvironmentRequest` schema.

**`@keyshade/api-client`**
- Remove existing `environment.types`.
- Change imports for environment types to `@keyshade/schema`. <br />

Related to #519

## Dependencies

Since old previous schemas required `CreateEnvironmentSchema`. The changes are made on top of #537 such that old `environment.ts` could be removed

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-11-16 21:07 UTC, muntaxir4 commented
Why are the PR tests failing? I can not find any such issue

2024-11-17 12:58 UTC, rajdip-b requested changes

2024-11-17 12:58 UTC, rajdip-b commented on packages/schema/src/index.ts
Can you get rid of the extra spaces?

2024-11-17 12:58 UTC, rajdip-b commented on packages/schema/src/index.types.ts
> +// Export types from environment.types.ts
Won't need these comments

2024-11-17 13:10 UTC, muntaxir4 commented on packages/schema/src/index.ts
Sure, I found it more readable.

2024-11-17 13:13 UTC, rajdip-b commented on packages/schema/src/index.ts
Ah

2024-11-18 10:14 UTC, rajdip-b commented
If you can make the changes, I'll get this merged asap.

2024-11-18 11:22 UTC, muntaxir4 commented
> If you can make the changes, I'll get this merged asap.

Made the required changes.

2024-11-18 11:43 UTC, rajdip-b approved these changes

2024-11-18 11:43 UTC, merged