feat(schema, api-client): Migrate integration types and schemas to @keyshade/schema
keyshade-xyz/keyshade pull request #539
Opened 2024-11-16 21:51 UTC by muntaxir4

## Description

**`@keyshade/schema`**
- Add schemas and types for integration.
- Add tests for integration schemas.
- Export integration schemas from `index` and its types  from `index.types` 

**`@keyshade/api-client`**
- Remove existing `integration.types`.
- Change imports for integration types to `@keyshade/schema`.  <br />

Related to #519

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-11-17 12:53 UTC, rajdip-b requested changes

2024-11-17 12:53 UTC, rajdip-b commented on packages/schema/src/index.types.ts
> +// Export types from secret.types.ts
You can get rid of this comment I feel

2024-11-17 12:53 UTC, rajdip-b commented on packages/schema/src/index.ts
Now that i see this, I have another suggestion in my mind. Instead of following the pattern of `module.ts` and `module.types.ts`, we can just use `index.ts` and `index.d.ts` since we already have the module name in the folder. Using this pattern should help us just use `./module` in imports and not `./module/module`. Can you try making this change for all the modules and lmk how it turns out?

2024-11-17 13:10 UTC, muntaxir4 commented on packages/schema/src/index.ts
If I create .d.ts then it wont be compiled. Are you pointing to the imports in api-schemas, since in api-client all imports are done with `@keyshade/api-schema` only?

2024-11-17 13:12 UTC, rajdip-b commented on packages/schema/src/index.ts
Nah, I'm talking about `schemas` folder. And sorry about the typo, i was meaning `index.types.ts`, not `index.d.ts`.

2024-11-17 13:36 UTC, muntaxir4 commented on packages/schema/src/index.ts
Yeah, index.types.ts would do.

2024-11-18 11:43 UTC, rajdip-b approved these changes

2024-11-18 11:52 UTC, rajdip-b approved these changes

2024-11-18 11:52 UTC, merged