feat(schema, api-client): Migrate workspace-membership schemas and types to @keyshade/schema
keyshade-xyz/keyshade pull request #569
Opened 2024-11-30 14:08 UTC by muntaxir4

## Description

**`@keyshade/schema`**
- Add schemas and types for `workspace-membership`.
- Add tests for `workspace-membership` schemas.
- Export workpsace-membership schemas from `index` and its types  from `index.types` .

**`@keyshade/api-client`**
- Remove existing `workspace-membership.types.d.ts`.
- Change imports for workpsace-membership types to `@keyshade/schema`.  And include userEmails for removeUsers.
- Modify DELETE request to contain optional body.<br />

Related to #519

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [x] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-12-01 06:17 UTC, rajdip-b requested changes

2024-12-01 06:17 UTC, rajdip-b commented on api-collection/Workspace Membership Controller/Remove users from workspace.bru
> +body:json {
Yeah, we need to update this as query params.

2024-12-02 19:47 UTC, muntaxir4 commented on packages/api-client/src/controllers/workspace-membership.ts
>      )
I have used userEmails as comma separated emails.

2024-12-03 05:04 UTC, rajdip-b approved these changes

2024-12-03 05:09 UTC, rajdip-b approved these changes

2024-12-03 05:09 UTC, merged