feat(api): Add endpoint to fetch all workspace invitations for a user
keyshade-xyz/keyshade pull request #586
Opened 2024-12-09 21:32 UTC by muntaxir4

## Description

Created an endpoint /invitations under workspace to retrieve all invitations for user with isAccepted filter. E2E Tests were also added.<br />

Fixes #404 

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-12-09 21:47 UTC, muntaxir4 commented
Something fishy with the api e2e tests. I push the changes only after testing it locally.

2024-12-09 22:23 UTC, muntaxir4 commented
Related to #550

2024-12-09 22:29 UTC, muntaxir4 commented
Any idea how to get the invitationDate? The WorkSpaceMember Table has no Date property

2024-12-10 10:03 UTC, rajdip-b commented
> Any idea how to get the invitationDate? The WorkSpaceMember Table has no Date property

You can add an `invitedOn` field to it i suppose.

2024-12-10 10:10 UTC, rajdip-b requested changes

2024-12-10 10:10 UTC, rajdip-b commented on apps/api/src/workspace/service/workspace.service.ts
> +   * Gets all workspaces of a user, paginated.
Gets all the invitations a user has to various workspaces

2024-12-10 10:10 UTC, rajdip-b commented on apps/api/src/workspace/service/workspace.service.ts
> +    isAccepted: boolean | undefined
Don't bother about this field. We always want to fetch the ones that have `isInvitationAccepted` set to `false`

2024-12-10 10:10 UTC, rajdip-b commented on apps/api/src/workspace/service/workspace.service.ts
> +        invitationAccepted: isAccepted,
This would always be false

2024-12-10 10:10 UTC, rajdip-b commented on apps/api/src/workspace/service/workspace.service.ts
> +        roles: {
Don't bother about the roles aswell.

2024-12-10 10:10 UTC, rajdip-b commented on apps/api/src/workspace/service/workspace.service.ts
> +                name: true
The role color should also come in handy

2024-12-11 21:33 UTC, muntaxir4 commented
> You can add an `invitedOn` field to it i suppose.

I added createdOn in the WorkspaceMember model, as I felt admin entries should not have invitedOn.

2024-12-12 11:47 UTC, rajdip-b approved these changes

2024-12-12 11:48 UTC, rajdip-b commented
@muntaxir4 can you please add the bruno docs aswell?

2024-12-13 04:25 UTC, rajdip-b approved these changes

2024-12-13 04:26 UTC, merged

2025-01-23 15:07 UTC, rajdip-b commented
:tada: This PR is included in version 2.9.0 :tada:

The release is available on [GitHub release](https://github.com/keyshade-xyz/keyshade/releases/tag/v2.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: