fix: remove await to send email async
keyshade-xyz/keyshade pull request #70
Opened 2024-01-02 19:28 UTC by lakshay-saini-au8

## Description

Remove await keywords while sending email so that we can send it async.

Fixes #63 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

@rajdip-b 

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR
- [x] There are no UI/UX issues

### Documentation Update

- [ ] This PR requires an update to the documentation at [docs.keyshade.xyz](https://docs.keyshade.xyz)
- [ ] I have made the necessary updates to the documentation, or no documentation changes are required.

2024-01-02 19:32 UTC, rajdip-b commented
I'll review this PR first thing in the morning tomorrow. Logged off just now :/

2024-01-03 04:34 UTC, rajdip-b requested changes

2024-01-03 04:34 UTC, rajdip-b commented on apps/api/src/auth/auth.service.ts
> +    this.resend.sendOtp(email, otp.code)
The file is now situated under `src/auth/service` folder. I forgot to make the push yesterday, so please make sure to do this change

2024-01-03 04:34 UTC, rajdip-b commented on apps/api/src/resend/services/mail.resend.ts
> +    this.sendEmail(email, subject, body)
Lines 39 and 67 also contain the same thing, you can remove those aswell

2024-01-03 05:13 UTC, rajdip-b commented
For resolving the merge conflict, you can just remove the `suth.service.ts` file inside the root of `auth` module

2024-01-03 11:24 UTC, kriptonian1 commented
@rajdip-b why are we taking contri on resend, haven't we planed to went with nodemailer

2024-01-03 11:51 UTC, rajdip-b commented
> @rajdip-b why are we taking contri on resend, haven't we planed to go with `nodemailer`

this isnt specific to resend. the only change nodemailer integration will do has got nothing to do with doing this, apart from renaming the variables. so i guess we will be cool

2024-01-03 12:11 UTC, rajdip-b commented
Hey @lakshay-saini-au8 I'm closing this PR for now, we want to integrate nodemailer first before we make any other changes since that is breaking things. Once it's done, I'll ping you so that you can take up the issue again!

2024-01-03 12:11 UTC, closed without merging